### ISSUE TITLE
In what setting do you work?

### ISSUE THREAD

**Issue by rreusser** [yoshuawuyts/ama#3]
Not geographically, more… ergonomically?

**Comment by yoshuawuyts** [comment]
Heya; neato question. As you may or may not know I have a history with RSI. This
is a quite common condition for us programmers to develop; but it's definitely
made me realize I had to invest in better posture / gear to match. If you do
something for the majority of your waking hours and like is your main source of
income it's worth investing in not getting injured I think. Hah.

I generally work from cafes, kind of conforming to whatever they provide. I try
and work as ergonomically but that doesn't always work out for me. I run a 12"
macbook, and while the screen size is fine for me the built in keyboard is
pretty horrible. That's why I always pack an external keyboard (magic keyboard)
and use a laptop stand (Roost). The latter helps a lot to reduce strain on my
back and neck, forcing me to take a better posture.

I used to work heaps from bed / couches also but that's contributed to my RSI
in such a degree that I've stopped doing that. When at home I work from a desk
and recently picked up an Ergodox EZ to make sure I change wrist posture when
at home. Diversity is the key to not getting like horrible RSI so umm yeah,
working on that.

Also one other thing I recently picked up is the Timeout App - it forces me to
take micro breaks every 2 mins, and longer breaks every 30. That's helped a lot
with managing RSI and since I've started using it in November my symptoms have
been drastically reduced.

Hope this answers your question; thanks again for asking!

### Gear
- [roost laptop stand](https://www.therooststand.com/)
- [ergodox EZ](https://ergodox-ez.com/)
- [magic keyboard](http://www.apple.com/shop/product/MLA22LL/A/magic-keyboard-us-english)
- [timeout app](http://www.dejal.com/timeout/)
- [orochi mouse](http://www.razerzone.com/gaming-mice/razer-orochi)

**Comment by rreusser** [comment]
Thanks for the detailed response! Just curious. I got the sense that you work mainly from cafes, so was curious what sort of physical constraints it requires to actually work effectively. That's a big hiccup for me currently: dealing every day with wondering where I'll be working. More of a mental burden than a physical burden, really.

**Comment by yoshuawuyts** [comment]
I have my regular spots in Berlin; it can be a bit more challenging to find
good spots in new places but once I've found a good one I tend to come back

**Comment by yoshuawuyts** [comment]
Doing an issue cleanup; closing for now!
